-- MySQL Script generated by MySQL Workbench
-- Mon May 25 16:48:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vtc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vtc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vtc` DEFAULT CHARACTER SET utf8 ;
USE `vtc` ;

-- -----------------------------------------------------
-- Table `vtc`.`association_vehicule_conducteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtc`.`association_vehicule_conducteur` (
  `id_association` INT(11) NOT NULL AUTO_INCREMENT,
  `id_vehicule` INT(11) NULL DEFAULT NULL,
  `id_conducteur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_association`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vtc`.`conducteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtc`.`conducteur` (
  `id_conducteur` INT(11) NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_conducteur`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vtc`.`vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtc`.`vehicule` (
  `id_vehicule` INT(11) NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(45) NULL DEFAULT NULL,
  `modele` VARCHAR(45) NULL DEFAULT NULL,
  `couleur` VARCHAR(45) NULL DEFAULT NULL,
  `immatriculation` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_vehicule`))
ENGINE = InnoDB
AUTO_INCREMENT = 510
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
